### ISSUE TITLE
Decrypt &Dump不会对Extension进行解密

### ISSUE THREAD

**Issue by ljh740** [Co2333/iOSreExtension#1]
在Extension 里面的文件 cryptid 1

**Comment by Lakr233** [comment]
会解密的啊 脚本是frida-iOS-dump的集成

**Comment by ljh740** [comment]
[Uploading Quantumult.zip…]()
样本

**Comment by ljh740** [comment]
[Quantumult.zip](https://github.com/Co2333/iOSreExtension/files/4229809/Quantumult.zip)
样本 PlugIns/Quantumult Network Extension.appex/Quantumult Network Extension
otool -l Quantumult\ Network\ Extension.appex/Quantumult\ Network\ Extension |grep "cmd LC_ENCRYPTION_INFO" -A 4
          cmd LC_ENCRYPTION_INFO_64
      cmdsize 24
     cryptoff 16384
    cryptsize 1589248

**Comment by Lakr233** [comment]
我瞅瞅

**Comment by Co2333** [comment]
你再砸一次试试？这边可以跑起来了

![截屏2020-04-23下午5 04 17](https://user-images.githubusercontent.com/25259084/80080645-7b5b9c00-8584-11ea-946f-88ecbf01d062.png)

**Comment by Lakr233** [comment]
Fixed in b6d314163ae5df1461708d577263ba8a3146c395

make sure to npm install -g bagbak
