### ISSUE TITLE
[Tip] Search Application

### ISSUE THREAD

**Issue by ufolux** [Co2333/iOSreExtension#11]
There is a great number of applications on my iPhone. I have to scroll the application list to find out which is the application that I need to work with. It's better to make a search bar for finding the target app quicker.

**Comment by iOSleep** [comment]
when you open the app, use refresh and it will listed on the top

**Comment by Lakr233** [comment]
Already exists

Select any app and press your keyboard for magic.

![截屏2020-07-11 上午9 23 52](https://user-images.githubusercontent.com/25259084/87213523-3d3a7100-c358-11ea-84eb-710c8577d92d.png)

**Comment by ufolux** [comment]
Great!
