### ISSUE TITLE
unc0ver和checkra1n ios12 ,ios13 越狱lldb链接失败

### ISSUE THREAD

**Issue by handeslfy** [Co2333/iOSreExtension#5]
hand@hands-iMac-Pro voltron %  echo 'If anything went wrong, make sure to have debugserver installed on your iDevice then restart the app and try again'
If anything went wrong, make sure to have debugserver installed on your iDevice then restart the app and try again
hand@hands-iMac-Pro voltron %  iproxy 2878 2878 &
[1] 19212
hand@hands-iMac-Pro voltron %  lldb
waiting for connection
The "sbr" python command has been installed and is ready for use.
test tgs
(lldb)  process connect connect://127.0.0.1:2878
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 11 (serial: c29c56c9fb7481ff1b69e289d45c5fe3f5b772ba), port 2878
Error connecting to device!
error: failed to get reply to handshake packet
(lldb) 

奇美拉越狱可以链接上。
issh的lldb可以成功附加。不知道啥原因。

**Comment by Lakr233** [comment]
debugserver 你确定装了吗 我这边所有越狱都没有这些问题的说

可以尝试的方案 
-点一下Shutdown iProxy然后重来
-关掉VSC重来
-检查ssh连接速度 如果执行超过3秒可能就悬了

**Comment by Lakr233** [comment]
![截屏2020-03-02下午5 16 29](https://user-images.githubusercontent.com/25259084/75662168-9ce98700-5ca9-11ea-957d-71c2971d1fc6.png)

**Comment by Lakr233** [comment]
问题已找到 你多点了几次

https://github.com/Co2333/iOSreExtension/commit/b87a40bb4ab014192e6edd492e1ee7bd2ac1e87d
