### ISSUE TITLE
libswiftCore.dylib not loaded

### ISSUE THREAD

**Issue by MrChens** [Co2333/iOSreExtension#8]
Manually installed package --->done

but vscode notice me the following tips:

> EXECUTE_COMMAND_ERROR -> stderr:dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib
>   Referenced from: /Users/mrchens/Library/Application Support/Code/User/globalStorage/lakr233.wikiqaqiosre/lkbins/bins/local/lsdevs
>   Reason: image not found
>  -> stdout: -> whenExec:'/Users/mrchens/Library/Application Support/Code/User/globalStorage/lakr233.wikiqaqiosre/lkbins/bins/local/lsdevs'  ==> Install dependency may solve the problem.
>

**Comment by Lakr233** [comment]
啊啊啊啊我真的不想把这几个基础wrapper重新写一遍 我去找找看solution

**Comment by Lakr233** [comment]
看一下这个能不能跑起来
[lsdevs.zip](https://github.com/Co2333/iOSreExtension/files/4318942/lsdevs.zip)

**Comment by Lakr233** [comment]
[swift.zip](https://github.com/Co2333/iOSreExtension/files/4319007/swift.zip)

**Comment by Lakr233** [comment]
https://apple.stackexchange.com/questions/93573/how-to-reinstall-xcode-command-line-tools

`sudo rm -rf /Library/Developer/CommandLineTools`
`xcode-select --install`

**Comment by MrChens** [comment]
> https://apple.stackexchange.com/questions/93573/how-to-reinstall-xcode-command-line-tools
> 
> `sudo rm -rf /Library/Developer/CommandLineTools`
> `xcode-select --install`

3Q, I will try it later.
