### ISSUE TITLE
Applications功能报错 EXECUTE_PYTHON_ERROR

### ISSUE THREAD

**Issue by Vxer-Lee** [Co2333/iOSreExtension#9]
手机:iPhone7
系统版本:iOS13.4.1
用Checkra1n 越狱

APPLICATIONS报错：
`EXECUTE_PYTHON_ERROR -> stderr:-> Failed to enumerate applications: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
 -> stdout: -> whenExec:'/Users/lee/Library/Application Support/Code/User/globalStorage/lakr233.wikiqaqiosre/lkbins/bins/py3/lsapps.py' 0ce588e7558891fe0605b446e73d0ab2c8feb0d1  ==> Install dependency may solve the problem.`

**Comment by Lakr233** [comment]
Failed to enumerate applications: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

可能是 手机没有信任 或者手机端的环境存在问题

一般来说 用Xcode跑个App就能解决问题 或者打开终端输入 ideviceimagemounter

如果问题依然存在 请考虑更新一下libimobiledevice
```
brew uninstall --ignore-dependencies libimobiledevice usbmuxd
brew install -v --HEAD --build-from-source usbmuxd libimobiledevice
```

**Comment by Vxer-Lee** [comment]
感谢大佬，最新的libimobiledevice是1.2.1么，用1.2.0可不可以，因为我1.2.1的编译报错，没编译出来

`Error: libimobiledevice HEAD-80eec8b did not build
Logs:
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/02.configure
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/00.options.out
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/02.configure.cc
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/03.make.cc
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/config.log
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/03.make
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh
     /Users/lee/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh.cc
READ THIS: https://docs.brew.sh/Troubleshooting
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC`

![截屏2020-05-22下午2 27 01](https://user-images.githubusercontent.com/27657137/82637883-536d6000-9c38-11ea-864d-dbbb3af61375.png)

[03.make.txt](https://github.com/Co2333/iOSreExtension/files/4666430/03.make.txt)

**Comment by Lakr233** [comment]
homebrew不要开加速用官方地址去build试试？

既然问题出现了就不能懒人咯

**Comment by Vxer-Lee** [comment]
感谢！
